name: Promote to Cloud Run (prod)
on:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    env:
      PROJECT_ID: github-automation-470314
      GAR_LOCATION: asia-south1
      REPO_NAME: apps
      IMAGE_NAME: ifra-build-deploy
      SERVICE_ACCOUNT_EMAIL: gh-actions-ar-writer@github-automation-470314.iam.gserviceaccount.com
      WIF_PROVIDER: projects/755744988797/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-provider
      RUN_SERVICE_NAME: ifra-build-deploy
      RUN_REGION: asia-south1
    steps:
      - uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}
      - uses: google-github-actions/setup-gcloud@v2
      - name: Deploy :latest
        run: |
          IMAGE="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest"
          gcloud run deploy "${{ env.RUN_SERVICE_NAME }}" --image="$IMAGE" --region="${{ env.RUN_REGION }}" --allow-unauthenticated --platform=managed
